=== Smrity-Thapa33/Web_Technology_Labs/Lab-4/02_employee.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="Employees">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="Employee" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Name" type="xs:string"/>
                            <xs:element name="Address" type="xs:string"/>
                            <xs:element name="Phone" type="xs:string"/>
                            <xs:element name="Designation" type="xs:string"/>
                            <xs:element name="Salary" type="xs:integer"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Smrity-Thapa33/Web_Technology_Labs/Lab-4/02_employee.xml
<?xml version="1.0" encoding="UTF-8"?>

<Employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="02_employee.xsd">

    <Employee>
        <Name>Ram Sharma</Name>
        <Address>Kathmandu</Address>
        <Phone>9812345678</Phone>
        <Designation>Manager</Designation>
        <Salary>50000</Salary>
    </Employee>

    <Employee>
        <Name>Sita Rai</Name>
        <Address>Lalitpur</Address>
        <Phone>9800000000</Phone>
        <Designation>Developer</Designation>
        <Salary>40000</Salary>
    </Employee>

</Employees>
